package com.jadic.ws.czsmk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-21T10:09:30.550+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://10.0.4.116:9900/CenterProcess.wsdl", name = "CenterProcessPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CenterProcessPortType {

    /**
     * Service definition of function ns__callback
     */
    @WebResult(name = "output", targetNamespace = "http://10.0.4.116:9900/CenterProcess.wsdl", partName = "output")
    @WebMethod
    public java.lang.String callback(
        @WebParam(partName = "input", name = "input")
        java.lang.String input
    );
}
